// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:tally/models/habit.dart';
import 'package:tally/models/habit_log.dart';
import 'package:tally/models/journal_entry.dart';
import 'package:tally/models/mood_entry.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HabitAdapter());
    registerAdapter(HabitLogAdapter());
    registerAdapter(JournalEntryAdapter());
    registerAdapter(MoodEntryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HabitAdapter());
    registerAdapter(HabitLogAdapter());
    registerAdapter(JournalEntryAdapter());
    registerAdapter(MoodEntryAdapter());
  }
}
